version: "3"
services:
  db:
    image: postgres:12
    container_name: "clearn-code-db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password

  app:
    image: bref/php-81-fpm-dev:latest
    ports: [ '8000:8000' ]
    volumes:
        - .:/var/task
        - ./storage:/tmp
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public
      LAMBDA_TASK_ROOT: /var/task
    env_file:
      - .env
volumes:
  postgres_data: