service: clean-code-app

provider:
    name: aws
    runtime: provided.al2
    region: ap-northeast-1

plugins:
    - ./vendor/bref/bref

functions:
    web:
        handler: public/index.php
        description: 'Laravel application'
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            - httpApi: '*'

    artisan:
        handler: artisan
        description: 'Laravel Artisan'
        layers:
            - ${bref:layer.php-81}
            - ${bref:layer.console}

package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
        - '!storage/framework/cache/**'
        - '!storage/framework/views/**'
        - '!storage/framework/sessions/**'
        - '!.env'
        - '!.env.*'
        - '!.git/**'